### PR TITLE
Homework19

### PR DESCRIPTION
**Pull request by manasamohan16**

### CODE REVIEW

**Comment by Berichicko** [comment]
You got this problem, please correct it. 

image

HINT


Test status_en

Test failed_en

**Comment by manasamohan16** [comment]
ok i corrected it

**Comment by Berichicko** [comment]
> ok i corrected it

Please, re-submit homework for review

**Comment by manasamohan16** [comment]
how do i create a new pull request

**Comment by Berichicko** [comment]
> how do i create a new pull request

**Work with GitHub pull requests**  https://www.jetbrains.com/help/idea/work-with-github-pull-requests.html

**Comment by Berichicko** [comment]
Hello,

I have checked your homework 19, and I wanted to let you know that you're doing great! Keep up the excellent work!
Best wishes from the HW team (Alex, [aliaksandr@testpro.io](mailto:aliaksandr@testpro.io))!

804deb64dc406a20a75da05d91a1a69e

image

**Pull request merged**
